<a href="https://colab.research.google.com/github/hemanagasri/aimlLab/blob/main/assignment_1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("weatherHistory.csv")
df


Formatted Date        Summary Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain   
...                              ...            ...         ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy        rain   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy        rain   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy        rain   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy        rain   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy        rain   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary  
0                   1015.13       Partly cloudy throughout the day.  
1                   1015.63       Partly cloudy throughout the day.  
2                   1015.94       Partly cloudy throughout the day.  
3                   1016.41       Partly cloudy throughout the day.  
4                   1016.51       Partly cloudy throughout the day.  
...                     ...                                     ...  
96448               1014.36  Partly cloudy starting in the morning.  
96449               1015.16  Partly cloudy starting in the morning.  
96450               1015.66  Partly cloudy starting in the morning.  
96451               1015.95  Partly cloudy starting in the morning.  
96452               1016.16  Partly cloudy starting in the morning.  

[96453 rows x 12 columns]

In [ ]:
df.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96453.000000              96453.000000  96453.000000   
mean         11.932678                 10.855029      0.734899   
std           9.551546                 10.696847      0.195473   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96453.000000            96453.000000     96453.000000     96453.0   
mean           10.810640              187.509232        10.347325         0.0   
std             6.913571              107.383428         4.192123         0.0   
min             0.000000                0.000000         0.000000         0.0   
25%             5.828200              116.000000         8.339800         0.0   
50%             9.965900              180.000000        10.046400         0.0   
75%            14.135800              290.000000        14.812000         0.0   
max            63.852600              359.000000        16.100000         0.0   

       Pressure (millibars)  
count          96453.000000  
mean            1003.235956  
std              116.969906  
min                0.000000  
25%             1011.900000  
50%             1016.450000  
75%             1021.090000  
max             1046.380000

In [ ]:
df=df.drop(['Loud Cover','Daily Summary','Formatted Date'],axis=1)
df

Summary Precip Type  Temperature (C)  Apparent Temperature (C)  \
0      Partly Cloudy        rain         9.472222                  7.388889   
1      Partly Cloudy        rain         9.355556                  7.227778   
2      Mostly Cloudy        rain         9.377778                  9.377778   
3      Partly Cloudy        rain         8.288889                  5.944444   
4      Mostly Cloudy        rain         8.755556                  6.977778   
...              ...         ...              ...                       ...   
96448  Partly Cloudy        rain        26.016667                 26.016667   
96449  Partly Cloudy        rain        24.583333                 24.583333   
96450  Partly Cloudy        rain        22.038889                 22.038889   
96451  Partly Cloudy        rain        21.522222                 21.522222   
96452  Partly Cloudy        rain        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                   251.0          15.8263   
1          0.86            14.2646                   259.0          15.8263   
2          0.89             3.9284                   204.0          14.9569   
3          0.83            14.1036                   269.0          15.8263   
4          0.83            11.0446                   259.0          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                    31.0          16.1000   
96449      0.48            10.0947                    20.0          15.5526   
96450      0.56             8.9838                    30.0          16.1000   
96451      0.60            10.5294                    20.0          16.1000   
96452      0.61             5.8765                    39.0          15.5204   

       Pressure (millibars)  
0                   1015.13  
1                   1015.63  
2                   1015.94  
3                   1016.41  
4                   1016.51  
...                     ...  
96448               1014.36  
96449               1015.16  
96450               1015.66  
96451               1015.95  
96452               1016.16  

[96453 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
l=preprocessing.LabelEncoder()
df['Summary']=l.fit_transform(df['Summary'])
df['Summary'].unique()


array([19, 17, 18, 12,  3,  6,  5,  4, 13, 15, 23, 25,  2, 26,  0, 11, 24,
        7,  9, 21, 14, 16,  8, 22, 10,  1, 20])

In [ ]:
df

Summary Precip Type  Temperature (C)  Apparent Temperature (C)  \
0           19        rain         9.472222                  7.388889   
1           19        rain         9.355556                  7.227778   
2           17        rain         9.377778                  9.377778   
3           19        rain         8.288889                  5.944444   
4           17        rain         8.755556                  6.977778   
...        ...         ...              ...                       ...   
96448       19        rain        26.016667                 26.016667   
96449       19        rain        24.583333                 24.583333   
96450       19        rain        22.038889                 22.038889   
96451       19        rain        21.522222                 21.522222   
96452       19        rain        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                   251.0          15.8263   
1          0.86            14.2646                   259.0          15.8263   
2          0.89             3.9284                   204.0          14.9569   
3          0.83            14.1036                   269.0          15.8263   
4          0.83            11.0446                   259.0          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                    31.0          16.1000   
96449      0.48            10.0947                    20.0          15.5526   
96450      0.56             8.9838                    30.0          16.1000   
96451      0.60            10.5294                    20.0          16.1000   
96452      0.61             5.8765                    39.0          15.5204   

       Pressure (millibars)  
0                   1015.13  
1                   1015.63  
2                   1015.94  
3                   1016.41  
4                   1016.51  
...                     ...  
96448               1014.36  
96449               1015.16  
96450               1015.66  
96451               1015.95  
96452               1016.16  

[96453 rows x 9 columns]

In [ ]:
df['Precip Type']=l.fit_transform(df['Precip Type'])
df['Precip Type'].unique()

array([0, 1, 2])

In [ ]:
df

Summary  Precip Type  Temperature (C)  Apparent Temperature (C)  \
0           19            0         9.472222                  7.388889   
1           19            0         9.355556                  7.227778   
2           17            0         9.377778                  9.377778   
3           19            0         8.288889                  5.944444   
4           17            0         8.755556                  6.977778   
...        ...          ...              ...                       ...   
96448       19            0        26.016667                 26.016667   
96449       19            0        24.583333                 24.583333   
96450       19            0        22.038889                 22.038889   
96451       19            0        21.522222                 21.522222   
96452       19            0        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                   251.0          15.8263   
1          0.86            14.2646                   259.0          15.8263   
2          0.89             3.9284                   204.0          14.9569   
3          0.83            14.1036                   269.0          15.8263   
4          0.83            11.0446                   259.0          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                    31.0          16.1000   
96449      0.48            10.0947                    20.0          15.5526   
96450      0.56             8.9838                    30.0          16.1000   
96451      0.60            10.5294                    20.0          16.1000   
96452      0.61             5.8765                    39.0          15.5204   

       Pressure (millibars)  
0                   1015.13  
1                   1015.63  
2                   1015.94  
3                   1016.41  
4                   1016.51  
...                     ...  
96448               1014.36  
96449               1015.16  
96450               1015.66  
96451               1015.95  
96452               1016.16  

[96453 rows x 9 columns]

In [ ]:
df.isnull().sum()

Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Pressure (millibars)        0
dtype: int64

In [ ]:
df['Wind Speed (km/h)'].fillna(value=df['Wind Speed (km/h)'].mean(),inplace=True)
df

Summary  Precip Type  Temperature (C)  Apparent Temperature (C)  \
0           19            0         9.472222                  7.388889   
1           19            0         9.355556                  7.227778   
2           17            0         9.377778                  9.377778   
3           19            0         8.288889                  5.944444   
4           17            0         8.755556                  6.977778   
...        ...          ...              ...                       ...   
96448       19            0        26.016667                 26.016667   
96449       19            0        24.583333                 24.583333   
96450       19            0        22.038889                 22.038889   
96451       19            0        21.522222                 21.522222   
96452       19            0        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                   251.0          15.8263   
1          0.86            14.2646                   259.0          15.8263   
2          0.89             3.9284                   204.0          14.9569   
3          0.83            14.1036                   269.0          15.8263   
4          0.83            11.0446                   259.0          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                    31.0          16.1000   
96449      0.48            10.0947                    20.0          15.5526   
96450      0.56             8.9838                    30.0          16.1000   
96451      0.60            10.5294                    20.0          16.1000   
96452      0.61             5.8765                    39.0          15.5204   

       Pressure (millibars)  
0                   1015.13  
1                   1015.63  
2                   1015.94  
3                   1016.41  
4                   1016.51  
...                     ...  
96448               1014.36  
96449               1015.16  
96450               1015.66  
96451               1015.95  
96452               1016.16  

[96453 rows x 9 columns]

In [ ]:
df['Wind Bearing (degrees)'].fillna(value=df['Wind Bearing (degrees)'].mean(),inplace=True)
df

Summary  Precip Type  Temperature (C)  Apparent Temperature (C)  \
0           19            0         9.472222                  7.388889   
1           19            0         9.355556                  7.227778   
2           17            0         9.377778                  9.377778   
3           19            0         8.288889                  5.944444   
4           17            0         8.755556                  6.977778   
...        ...          ...              ...                       ...   
96448       19            0        26.016667                 26.016667   
96449       19            0        24.583333                 24.583333   
96450       19            0        22.038889                 22.038889   
96451       19            0        21.522222                 21.522222   
96452       19            0        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                   251.0          15.8263   
1          0.86            14.2646                   259.0          15.8263   
2          0.89             3.9284                   204.0          14.9569   
3          0.83            14.1036                   269.0          15.8263   
4          0.83            11.0446                   259.0          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                    31.0          16.1000   
96449      0.48            10.0947                    20.0          15.5526   
96450      0.56             8.9838                    30.0          16.1000   
96451      0.60            10.5294                    20.0          16.1000   
96452      0.61             5.8765                    39.0          15.5204   

       Pressure (millibars)  
0                   1015.13  
1                   1015.63  
2                   1015.94  
3                   1016.41  
4                   1016.51  
...                     ...  
96448               1014.36  
96449               1015.16  
96450               1015.66  
96451               1015.95  
96452               1016.16  

[96453 rows x 9 columns]

In [ ]:
df.corr()

Summary  Precip Type  Temperature (C)  \
Summary                   1.000000    -0.116502         0.146658   
Precip Type              -0.116502     1.000000        -0.520381   
Temperature (C)           0.146658    -0.520381         1.000000   
Apparent Temperature (C)  0.142760    -0.521781         0.992629   
Humidity                 -0.113119     0.214330        -0.632255   
Wind Speed (km/h)         0.004258    -0.057435         0.008957   
Wind Bearing (degrees)    0.022789    -0.038971         0.029988   
Visibility (km)           0.140138    -0.307442         0.392847   
Pressure (millibars)      0.143405     0.012511        -0.005447   

                          Apparent Temperature (C)  Humidity  \
Summary                                   0.142760 -0.113119   
Precip Type                              -0.521781  0.214330   
Temperature (C)                           0.992629 -0.632255   
Apparent Temperature (C)                  1.000000 -0.602571   
Humidity                                 -0.602571  1.000000   
Wind Speed (km/h)                        -0.056650 -0.224951   
Wind Bearing (degrees)                    0.029031  0.000735   
Visibility (km)                           0.381718 -0.369173   
Pressure (millibars)                     -0.000219  0.005454   

                          Wind Speed (km/h)  Wind Bearing (degrees)  \
Summary                            0.004258                0.022789   
Precip Type                       -0.057435               -0.038971   
Temperature (C)                    0.008957                0.029988   
Apparent Temperature (C)          -0.056650                0.029031   
Humidity                          -0.224951                0.000735   
Wind Speed (km/h)                  1.000000                0.103822   
Wind Bearing (degrees)             0.103822                1.000000   
Visibility (km)                    0.100749                0.047594   
Pressure (millibars)              -0.049263               -0.011651   

                          Visibility (km)  Pressure (millibars)  
Summary                          0.140138              0.143405  
Precip Type                     -0.307442              0.012511  
Temperature (C)                  0.392847             -0.005447  
Apparent Temperature (C)         0.381718             -0.000219  
Humidity                        -0.369173              0.005454  
Wind Speed (km/h)                0.100749             -0.049263  
Wind Bearing (degrees)           0.047594             -0.011651  
Visibility (km)                  1.000000              0.059818  
Pressure (millibars)             0.059818              1.000000

In [ ]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [ ]:
y=df.iloc[:,1]
y

0        0
1        0
2        0
3        0
4        0
        ..
96448    0
96449    0
96450    0
96451    0
96452    0
Name: Precip Type, Length: 96453, dtype: int32

In [ ]:
X=df[['Apparent Temperature (C)','Temperature (C)']]
X


Apparent Temperature (C)  Temperature (C)
0                      7.388889         9.472222
1                      7.227778         9.355556
2                      9.377778         9.377778
3                      5.944444         8.288889
4                      6.977778         8.755556
...                         ...              ...
96448                 26.016667        26.016667
96449                 24.583333        24.583333
96450                 22.038889        22.038889
96451                 21.522222        21.522222
96452                 20.438889        20.438889

[96453 rows x 2 columns]

In [ ]:
#data normalization
X=preprocessing.StandardScaler().fit_transform(X)
X

array([[-0.32403547, -0.25759902],
       [-0.3390971 , -0.26981351],
       [-0.13810226, -0.26748694],
       ...,
       [ 1.04553403,  1.0580761 ],
       [ 0.99723295,  1.00398335],
       [ 0.89595648,  0.89056308]])

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)


In [ ]:
X_test.shape

(28936, 2)

In [ ]:
#training and predicting
knmodel=KNeighborsClassifier(n_neighbors=5)
knmodel.fit(X_train,y_train)


KNeighborsClassifier()

In [ ]:
y_predict=knmodel.predict(X_test)
y_predict

C:\Users\Jadam Harika\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#accuracy
from sklearn.metrics import accuracy_score


In [ ]:
acc=accuracy_score(y_test,y_predict)
acc

0.9936411390655239

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test.values,y_predict)
cm

array([[25524,    27,     0],
       [    5,  3228,     0],
       [  152,     0,     0]], dtype=int64)